name: "update_rates_latest"
description: "Fetch the latest exchange rates from Open Exchange Rates API and update Salesforce currencies."

inputs:
  OXR_APP_ID:
    description: "Open Exchange Rates API key"
    required: true
  SALESFORCE_EMAIL:
    description: "Salesforce email address"
    required: true
  SALESFORCE_PASSWORD:
    description: "Salesforce password"
    required: true
  SALESFORCE_TOKEN:
    description: "Salesforce security token"
    required: true
  SALESFORCE_DOMAIN:
    description: "Optional: 'test' for a sandbox, or a custom domain."
    required: false

runs:
  using: "docker"
  image: "../dockerfile"
  env:
    OXR_APP_ID: ${{ inputs.OXR_APP_ID }}
    SALESFORCE_EMAIL: ${{ inputs.SALESFORCE_EMAIL }}
    SALESFORCE_PASSWORD: ${{ inputs.SALESFORCE_PASSWORD }}
    SALESFORCE_TOKEN: ${{ inputs.SALESFORCE_TOKEN }}
    SALESFORCE_DOMAIN: ${{ inputs.SALESFORCE_DOMAIN }}
  args:
    - "python"
    - "/action/update_rates_latest/main.py"