name: "Update Salesforce Currencies Action"
description: "A composite GitHub Action that fetches the latest exchange rates from Open Exchange Rates API and updates Salesforce."

inputs:
  SALESFORCE_EMAIL:
    description: "Salesforce email address"
    required: true
  SALESFORCE_PASSWORD:
    description: "Salesforce password"
    required: true
  SALESFORCE_TOKEN:
    description: "Salesforce security token"
    required: true
  OXR_APP_ID:
    description: "Open Exchange Rates API key"
    required: true
  SALESFORCE_SANDBOX:
    description: "Salesforce sandbox name (optional)"
    required: false

runs:
  using: "docker"
  image: "../dockerfile"
  env:
    OXR_APP_ID: ${{ inputs.OXR_APP_ID }}
    SALESFORCE_EMAIL: ${{ inputs.SALESFORCE_EMAIL }}
    SALESFORCE_PASSWORD: ${{ inputs.SALESFORCE_PASSWORD }}
    SALESFORCE_TOKEN: ${{ inputs.SALESFORCE_TOKEN }}
    SALESFORCE_SANDBOX: ${{ inputs.SALESFORCE_SANDBOX }}
  args:
    - "python"
    - "update_rates_latest.py"