name: "Update Exchange Rates"
on:
  workflow_dispatch:

jobs:
  update_rates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Update Rates Action
        uses: ./update_rates_latest
        with:
          SALESFORCE_EMAIL: ${{ secrets.SALESFORCE_EMAIL }}
          SALESFORCE_PASSWORD: ${{ secrets.SALESFORCE_PASSWORD }}
          SALESFORCE_TOKEN: ${{ secrets.SALESFORCE_TOKEN }}
          OXR_APP_ID: ${{ secrets.OXR_APP_ID }}
